[package]
name = "reoserv"
version = "0.1.0"
authors = ["Richard Leek <richard@richardleek.com>"]
edition = "2018"

[features]
console = ["console-subscriber"]

[dependencies]
config = { version = "0.11", features = ["toml"] }
chrono = "0.4"
lazy_static = "1.0"
log = "0.4"
num-traits = "0.2"
pretty_env_logger = "0.4"
futures = "0.3"
tokio = { version = "1", features = ["full", "tracing"] }
serde_derive = "^1.0.8"
serde = "^1.0.8"
console-subscriber = { version = "0.1", optional = true }
mysql_async = "0.29"
sha2 = "0.10"
eo = { git = "https://github.com/sorokya/eo" }
rand = "0.8"