[package]
name = "reoserv2"
version = "0.1.0"
authors = ["Richard Leek <richard@richardleek.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
num-traits = "0.2"
pretty_env_logger = "0.3"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
eo = { path = "../eo" }