[package]
name = "reoserv"
version = "0.1.0"
authors = ["Richard Leek <richard@richardleek.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { version = "0.11", features = ["toml"] }
lazy_static = "1.0"
log = "0.4"
num-traits = "0.2"
pretty_env_logger = "0.4"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
serde_derive = "^1.0.8"
serde = "^1.0.8"
eo = { git = "https://github.com/sorokya/eo" }