[server]
# Host IP the server will listen for incoming connections on
host = "0.0.0.0"

# Host Port the server will listen for incoming connections on
port = "8078"

# Maximum amount of connections to allow to the server
max_connections = 300

# How often to send a ping to connected clients
# clients are disconnected if they fail to respond to the first
# ping before the next one is sent.
ping_rate = 60

# The salt value used when hashing account passwords
# This should be changed to a random value to prevent
# rainbow table attacks
password_salt = "ChangeMe"

# Validate the sequence number sent by the client
# matches the one on the server
enforce_sequence = true

# Number of maps to attempt to load
num_of_maps = 282

# Initial location and home for new characters
[new_character]
spawn_map = 192
spawn_x = 6
spawn_y = 6
# 0 = Down, 1 = Left, 2 = Up, 3 = Right
spawn_direction = 0
home = "Wanderer"

[jail]
map = 176
x = 1
y = 1

[world]
# Size of the characters view port
see_distance = 11

[npcs]
# Should NPCs spawn immediately when the server starts?
# if false they will spawn after their respawn time
instant_spawn = false

# Should NPCs stand still if there are no players on their map?
# if false they will always act even if there are no players
freeze_on_empty_map = true

# Respawn rate of NPCs in seconds
respawn_rate = 1

# Rate at which NPCs act (move, attack, speak) in miliseconds
act_rate = 50

# Speed in miliseconds for each npc spawn speed
speed_0 = 400
speed_1 = 400
speed_2 = 800
speed_3 = 1200
speed_4 = 2400
speed_5 = 4800
speed_6 = 9600

# Speed that NPCs talk at in miliseconds
talk_rate = 4800

[database]
host = "127.0.0.1"
port = "3306"
name = "reoserv"
username = "reoserv"
password = "reoserv"