[server]
# Host IP the server will listen for incoming connections on
host = "0.0.0.0"

# Host Port the server will listen for incoming connections on
port = "8078"

# Maximum amount of connections to allow to the server
max_connections = 300

# How often to send a ping to connected clients
# clients are disconnected if they fail to respond to the first
# ping before the next one is sent.
ping_rate = 60

# The salt value used when hashing account passwords
# This should be changed to a random value to prevent
# rainbow table attacks
password_salt = "ChangeMe"

# Validate the sequence number sent by the client
# matches the one on the server
enforce_sequence = true

# Number of maps to attempt to load
num_of_maps = 282

# Client version
min_version = "0.0.28"
max_version = "0.3.29"

# How often the server will save all online maps, and characters
# in minutes, 0 to disable
save_rate = 5

# Should the server generate pub files from JSON?
# If false you will need to provide binary pub files yourself
generate_pub = true

# Server language. Should match a ron file in the lang directory
lang = "en"

[database]
host = "127.0.0.1"
port = "3306"
name = "reoserv"
username = "reoserv"
password = "reoserv"

[sln]
enabled = false
url = "http://www.apollo-games.com/SLN/sln.php/"
site = ""
hostname = ""
server_name = "Untitled Server"
rate = 5
zone = ""

# Initial location and home for new characters
[new_character]
spawn_map = 192
spawn_x = 6
spawn_y = 6
# 0 = Down, 1 = Left, 2 = Up, 3 = Right
spawn_direction = 0
home = "Wanderer"

[jail]
map = 76
x = 6
y = 7
free_map = 76
free_x = 9
free_y = 11

[rescue]
map = 4
x = 24
y = 24

[world]
# Size of the characters view port
see_distance = 11

# Max distance a player can drop/pick up an item
drop_distance = 2

# How often players recover HP/TP in ticks
recover_rate = 720

# How often npcs recover HP/TP in ticks
npc_recover_rate = 840

# How often chests respawn in ticks
chest_spawn_rate = 480

# Apply a multipler to experience gains when killing NPCs
exp_multiplier = 1

stat_points_per_level = 3
skill_points_per_level = 4

# Global tick rate for the server in miliseconds
# Recommended not to change
tick_rate = 125

# Number of ticks before maps are checked for arena spawn
arena_spawn_rate = 8

# Number of ticks before maps are checked for open doors
door_close_rate = 8

# Amount of ticks before a player is "sucked" into a nearby warp
warp_suck_rate = 120

# How frequently timed drain events occur in ticks
drain_rate = 125

# Percentage of max HP that drain events will damage
drain_hp_damage = 0.1

# Percentage of max TP that drain events will damage
drain_tp_damage = 0.1

# How frequently earthquake events occur in ticks
quake_rate = 25

# How frequently timed spikes will activate (in ticks)
spike_rate = 12

# Percentage of max HP that spikes will damage
spike_damage = 0.2

[combat]

# Range of weapons, default is 1 if not specified
# arrows = false if the weapon does not require arrows
weapon_ranges = [
  { weapon = 297, range = 5, arrows = true },
  { weapon = 316, range = 5, arrows = true },
  { weapon = 457, range = 5, arrows = true },
  { weapon = 365, range = 10, arrows = false },
]

[map]

# Control the different type of quake map effects
# ticks are multiples of world.quake_rate
quakes = [
  { min_ticks = 3, max_ticks = 29, min_strength = 0, max_strength = 2 },
  { min_ticks = 3, max_ticks = 22, min_strength = 0, max_strength = 2 },
  { min_ticks = 3, max_ticks = 15, min_strength = 4, max_strength = 6 },
  { min_ticks = 2, max_ticks = 8, min_strength = 6, max_strength = 8 }
]

# Number of ticks before a door is closed
# This should be a multiple of world.door_close_rate
door_close_rate = 3

[npcs]
# Should NPCs spawn immediately when the server starts?
# if false they will spawn after their respawn time
instant_spawn = false

# How often NPCs will respawn in ticks
respawn_rate = 8

# Should NPCs stand still if there are no players on their map?
# if false they will always act even if there are no players
freeze_on_empty_map = true

# Should NPCs stand still if there are no nearby players?
# if false they will always act even if there are no nearby players
freeze_out_of_range = true

# Range in which an aggroed NPC will chase a player
chase_distance = 10

# Ticks until an aggroed NPC will give up chasing/attacking a player
bored_timer = 240

# How often in server ticks npcs should be checked for actions
act_rate = 5

# How often in server ticks npcs should be checked for combat and movement
# (This should be a multiple of npc tick_rate)
speed_0 = 5
speed_1 = 5
speed_2 = 10
speed_3 = 15
speed_4 = 30
speed_5 = 60
speed_6 = 120

# How often in server ticks npcs should be checked for speech
# (This should be a multiple of npc tick_rate)
talk_rate = 300

[bank]

# Maximum amount of an item a bank locker will hold
max_item_amount = 200

# Amount of items you can store in a locker before any upgrades
base_size = 25

# Number of extra items you can desposit each upgrade
size_step = 5

# Maximum amount of upgrades that can be bought
max_upgrades = 7

# Base price for bank upgrade
upgrade_base_cost = 1000

# Price increase for each upgrade
upgrade_cost_step = 1000

[limits]

# Maximum amount of gold a player can deposit
max_bank_gold = 2000000000

# Maximum amount of an item a player can have in their inventory
max_item = 2000000000

# Maximum amount of an item players can trade
max_trade = 2000000000

# Maximum amount of an item a chest will hold
max_chest = 10000000

# Maximum amount of players to one group
max_party_size = 9

[board]

# Maximum number of posts a board will hold before deleting old posts
max_posts = 20

# Maximum number of posts a user can have on a board at any one time
# Any less than 2 will not be enforced by the official client
max_user_posts = 6

# Maximum number of "recent" posts a user can have on a board
# Any less than 2 will not be enforced by the official client
max_recent_posts = 2

# Age of a post to be considered "recent" in minutes
recent_post_time = 30

# Maximum length of board post subjects
# Shouldn't be changed unless using a custom client which supports it
max_subject_length = 32

# Maximum length of board posts
max_post_length = 2048

# Adds "(x minutes ago)" text to every post on a board
date_posts = true

# Board number that reports/requests are logged (1 to 8)
# This board can't be accessed by players if placed in-game
admin_board = 5

# Maximum number of posts that the AdminBoard can hold
admin_max_posts = 100

[chest]

# Numbers of slots in a chest
slots = 5

[jukebox]

cost = 25

max_track_id = 20

# Number of seconds before the next track can be played
# 0 to allow tracks to be played instantly
track_timer = 90
