[server]
host = "0.0.0.0"
port = "8078"

# Maximum amount of connections to allow to the server
max_connections = 300

# How often to send a ping to connected clients
# clients are disconnected if they fail to respond to the first
# ping before the next one is sent.
ping_rate = 60

password_salt = "ChangeMe"

# Validate the sequence number sent by the client
# matches the one on the server
# Doesn't always work. Best to leave disabled until
# it's fixed.
enforce_sequence = false

[database]
host = "127.0.0.1"
port = "3306"
name = "reoserv"
username = "reoserv"
password = "reoserv"