services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: reoserv
      MYSQL_DATABASE: reoserv
      MYSQL_PASSWORD: ${MYSQL_REOSERV_PASSWORD}
      TZ: UTC
    ports:
      - "3306:3306"
    volumes:
      - ./db-init/:/docker-entrypoint-initdb.d/
